Refactor VtexGiftcardTransactionCancel
bawclothing/Loyalty pull request #11
Opened 2024-08-20 16:41 UTC by LeticiaRutsatz

2024-08-21 18:44 UTC, christianphilippe25 commented on Provider/func-LY-VtexGiftcardTransactionCancel/src/func.js
> +    const wallet = await getWalletById(walletId);
da pra fazer assincrono ambos e retornar como `const { order, wallet } = await Promise.all([getOrderById, getWalletById])`

2024-08-21 19:06 UTC, mairahanel approved these changes

2024-08-21 19:24 UTC, mairahanel requested changes

2024-08-21 19:24 UTC, mairahanel commented on Provider/func-LY-VtexGiftcardTransactionCancel/src/func.js
> +        `https://api.hubteam.com.br/loyalty/orders/${orderId}`,
Essa rota está depreciada. A List orders agora busca tanto por ID interno quanto externo.

`https://api.hubteam.com.br/loyalty/orders?internalOrderId=${orderId}`

2024-08-22 12:30 UTC, mairahanel approved these changes

2024-08-22 14:14 UTC, christianphilippe25 approved these changes

2024-08-22 16:15 UTC, merged