Refactor GetGiftcardById
bawclothing/Loyalty pull request #7
Opened 2024-08-19 20:47 UTC by LeticiaRutsatz

2024-08-20 12:08 UTC, samueldbo commented on Provider/func-LY-GetGiftcardById/src/func.js
> +      const response = await handleRequest(`https://dev.api.hubteam.com.br/security/secret`, init);
Faltou checar se é uma resposta válida

2024-08-20 19:37 UTC, christianphilippe25 requested changes

2024-08-20 19:37 UTC, christianphilippe25 commented on Provider/func-LY-GetGiftcardById/src/func.js
> +      return response;
ta retornando uma variavel nao declarada nesse escopo

2024-08-21 18:26 UTC, christianphilippe25 commented on Provider/func-LY-GetGiftcardById/src/func.js
> +      return response;
exato, o else nao é o mesmo escopo do if

2024-08-21 18:35 UTC, mairahanel approved these changes

2024-08-21 19:18 UTC, christianphilippe25 approved these changes

2024-08-22 14:14 UTC, merged